apiVersion: v1
kind: ServiceAccount
metadata:
  name: broker-sa
  namespace: cloudsoa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: broker-pod-reader
  namespace: cloudsoa
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: broker-pod-reader-binding
  namespace: cloudsoa
subjects:
  - kind: ServiceAccount
    name: broker-sa
    namespace: cloudsoa
roleRef:
  kind: Role
  name: broker-pod-reader
  apiGroup: rbac.authorization.k8s.io
